name: Acquire Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Acquire .alf file
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.1.6f1-ios-3.3.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Manual Activation File
        run: |
          unity-editor -batchmode -nographics -createManualActivationFile -logfile /dev/stdout || true
          mkdir -p output
          find / -name "*.alf" 2>/dev/null -exec cp {} output/ \; || true

      - name: Expose .alf file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.1.6f1.alf
          path: output/*.alf
